### ISSUE TITLE
Input/output examples

### ISSUE THREAD

**Issue by ai** [csstools/postcss-normalize#12]
Examples are still mandatory for this project too :). But it could be in pseudo code:

```css
.app { … } /* Your code */
```

```css
* { padding: 0; … } /* Normalize CSS */
.app { … } /* Your code */
```
