### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by ai** [csstools/postcss-normalize#15]
`package.json`:

```js
  "browserslist": ["last 1 edge version"],
  "postcss": {
    "plugins": {
      "autoprefixer": {},
      "postcss-normalize": {}
    }
  },
```

Output:

```css
hr {overflow: visible
}
abbr[title] {text-decoration: underline;text-decoration: underline dotted
}
b,
strong {font-weight: bolder
}
button,
input {overflow: visible
}
button,
select {text-transform: none
}
legend {box-sizing: border-box;color: inherit;display: table;max-width: 100%;padding: 0;white-space: normal
}
details {display: block
}
```

Expected output:

```css
hr {overflow: visible}
abbr[title] {text-decoration: underline;text-decoration: underline dotted}
b,strong {font-weight: bolder}
button,input {overflow: visible}
button,select {text-transform: none}
legend {box-sizing: border-box;color: inherit;display: table;max-width: 100%;padding: 0;white-space: normal}
details {display: block}
```
